steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/chatllm-demo/${IMAGE}:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/chatllm-demo/${IMAGE}:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${SERVICE_NAME}', '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/chatllm-demo/${IMAGE}:latest', '--region', '${REGION}', '--allow-unauthenticated', '--service-account','${SERVICE_ACC}']
images:
- us-central1-docker.pkg.dev/${PROJECT_ID}/chatllm-demo/${IMAGE}:latest